service:
    example_cxx_xmake:
        build: .
        image: example-cxx-xmake

networks:
    example_cxx_xmake-net:
        name: example_cxx_xmake-net
        ipam:
            config:
                -   subnet: 172.16.238.0/24
